kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: quotesweb-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quotesweb
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
